module.exports = [
    {
        "name" : "AAA",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Labrador Retriever",
        "age": "2",
        "sex": "female",
        "color": "brown",
        "temperament":"",
        "minTimePerDay": "1H",
        "likesToWalkWith": "Daniel",
        "allergies": "Nuts",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "BBB",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Pug",
        "age": "5",
        "sex": "male",
        "color": "white",
        "temperament":"",
        "minTimePerDay": "1H30M",
        "likesToWalkWith": "Jihyo",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "CCC",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Siberian Husky",
        "age": "3",
        "sex": "male",
        "color": "White and Black",
        "temperament":"",
        "minTimePerDay": "2H",
        "likesToWalkWith": "Wayne",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "DDD",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Bulldog",
        "age": "1",
        "sex": "female",
        "color": "White and Brown",
        "temperament":"",
        "minTimePerDay": "2H",
        "likesToWalkWith": "John",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "EEE",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Pomeranian",
        "age": "8",
        "sex": "male",
        "color": "White and Brown",
        "temperament":"",
        "minTimePerDay": "30M",
        "likesToWalkWith": "Brian",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "FFF",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Poodle",
        "age": "2",
        "sex": "female",
        "color": "Brown",
        "temperament":"",
        "minTimePerDay": "1H30M",
        "likesToWalkWith": "Victor",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "GGG",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Chow Chow",
        "age": "3",
        "sex": "female",
        "color": "Brown",
        "temperament":"",
        "minTimePerDay": "1H",
        "likesToWalkWith": "Kevin",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "HHH",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Maltese",
        "age": "2",
        "sex": "female",
        "color": "White",
        "temperament":"",
        "minTimePerDay": "1H20M",
        "likesToWalkWith": "Albert",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "III",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Boxer",
        "age": "1",
        "sex": "male",
        "color": "Black",
        "temperament":"",
        "minTimePerDay": "1H",
        "likesToWalkWith": "Justin",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      },
      {
        "name" : "JJJ",
        "animal": "canine",
        "lastWalked": 1568494598504,
        "breed": "Golden Retriever",
        "age": "10",
        "sex": "male",
        "color": "Gold",
        "temperament":"",
        "minTimePerDay": "40M",
        "likesToWalkWith": "Choi",
        "allergies": "",
        "notes": "",
        "map": "",
        "walking":false
      }
];